[package]
name = "tjh-mqtt-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.1", features = ["derive", "env"] }
mqtt = { path = "../lib", features = ["tokio-client", "tls", "url"], package = "tjh-mqtt"}
tokio = { workspace = true, features = ["rt", "signal", "macros"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.4.1"

[[bin]]
name = "mqtt"
path = "src/main.rs"
