[package]
name = "tjh-mqtt-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.1", features = ["derive", "env"] }
mqtt = { version = "0.3", path = "../lib", features = ["tokio-client", "tls"], package = "tjh-mqtt"}
tokio = { version = "1.32.0", features = ["rt", "signal", "macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[[bin]]
name = "mqtt"
path = "src/main.rs"
