[package]
name = "mqtt"
version = "0.0.1-pre-alpha"
edition = "2021"

[dependencies]
bytes = "1.4.0"
tokio = { version = "1.32.0", optional = true, features = ["net", "io-util", "macros", "sync", "time", "tracing", "rt-multi-thread"] }
tracing = { version = "0.1.37", optional = true }
tracing-subscriber = { version = "0.3.17", optional = true }

[features]
default = ["tokio", "tracing", "tracing-subscriber"]
tokio = ["dep:tokio", "tracing"]
