[package]
name = "mqtt-async"
version = "0.0.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
mqtt-core = { version = "*", path = "../mqtt-core" }
tokio = { version = "1.32", features = ["net", "io-util", "macros", "sync", "time", "tracing", "rt"] }
tracing = { version = "0.1" }
